# Generated by Django 4.2 on 2024-09-09 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_comment_name_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_pub',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
